name = "DeepSeek-V3-0324"
release_date = "2025-03-24"
last_updated = "2025-03-24"
attachment = false
reasoning = false
temperature = true
knowledge = "2024-10"
tool_call = true
open_weights = true

[cost]
input = 1.25
output = 1.25

[limit]
context = 16384
output = 8192

[modalities]
input = ["text"]
output = ["text"]
