name = "Claude Sonnet 4"
release_date = "2025-05-22"
last_updated = "2025-05-22"
attachment = true
reasoning = true
temperature = true
knowledge = "2025-03-31"
tool_call = true
open_weights = false

[limit]
context = 200_000
output = 8_192

[modalities]
input = ["text", "image"]
output = ["text"]
