name = "Claude Sonnet 3.5"
release_date = "2024-10-22"
last_updated = "2024-10-22"
attachment = true
reasoning = false
temperature = true
knowledge = "2024-04"
tool_call = true
open_weights = false

[limit]
context = 200_000
output = 8_192

[modalities]
input = ["text", "image"]
output = ["text"]
