name = "Claude Sonnet 3.7 Thinking"
release_date = "2025-02-19"
last_updated = "2025-02-19"
attachment = true
reasoning = true
temperature = true
knowledge = "2024-04"
tool_call = true
open_weights = false

[limit]
context = 200_000
output = 8_192

[modalities]
input = ["text", "image"]
output = ["text"]
