name = "DeepSeek Coder V2 Lite"
attachment = false
reasoning = false
tool_call = false
temperature = true
knowledge = "2021-09"
release_date = "2025-06-22"
last_updated = "2025-06-22"
open_weights = true

[cost]
input = 0.5
output = 2.0

[limit]
context = 131072
output = 8192

[modalities]
input = ["text"]
output = ["text"]
