name = "DeepSeek R1 671B"
attachment = false
reasoning = true
tool_call = false
temperature = true
knowledge = "2023-10"
release_date = "2025-06-05"
last_updated = "2025-06-05"
open_weights = true

[cost]
input = 3.5
output = 14.0

[limit]
context = 131072
output = 8192

[modalities]
input = ["text"]
output = ["text"]
