name = "Llama 3.1 405B"
attachment = false
reasoning = false
tool_call = false
temperature = true
knowledge = "2023-12"
release_date = "2025-06-30"
last_updated = "2025-06-30"
open_weights = true

[cost]
input = 1.5
output = 6.0

[limit]
context = 65536
output = 8192

[modalities]
input = ["text"]
output = ["text"]
