name = "Llama 3.2 3B"
attachment = false
reasoning = false
tool_call = true
temperature = true
knowledge = "2023-12"
release_date = "2025-05-23"
last_updated = "2025-05-23"
open_weights = true

[cost]
input = 0.15
output = 0.6

[limit]
context = 131072
output = 8192

[modalities]
input = ["text"]
output = ["text"]
