name = "Qwen 2.5 VL 72B"
attachment = false
reasoning = false
tool_call = false
temperature = true
knowledge = "2023-10"
release_date = "2025-06-09"
last_updated = "2025-06-09"
open_weights = true

[cost]
input = 0.7
output = 2.8

[limit]
context = 32768
output = 8192

[modalities]
input = ["text", "image"]
output = ["text"]
