name = "GPT OSS 20B"
release_date = "2025-08-05"
last_updated = "2025-08-05"
attachment = false
reasoning = true
temperature = true
tool_call = true
open_weights = true

[cost]
input = 0.05
output = 0.20

[limit]
context = 131_072
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
